#include <iostream>

int main()
{
	std::cout << "Throw exception!";
	return 0;
}